version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ignosi"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1t5l7j1zx79sy"
s3_prefix = "ignosi"
region = "us-east-1"
profile = "aws-asad"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
